#!/bin/bash
#
# Copyright 2014-2017 Telefonica Investigación y Desarrollo, S.A.U
# 
# This file is part of fiware-cygnus (FIWARE project).
# 
# fiware-cygnus is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any
# later version.
# fiware-cygnus is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
# 
# You should have received a copy of the GNU Affero General Public License along with fiware-cygnus. If not, see
# http://www.gnu.org/licenses/.
# 
# For those usages not covered by the GNU Affero General Public License please contact with iot_support at tid dot es
#
# cygnus         Start/Stop cygnus
#
# chkconfig: 2345 99 60
# description: cygnus
#

# Load some fancy functions for init.d
. /etc/rc.d/init.d/functions

PARAM=$1

CYGNUS_INSTANCE=${2}

COMPONENT_NAME=cygnus
PREFIX=/usr
CYGNUS_DIR=${PREFIX}/cygnus
FLUME_EXECUTABLE=${CYGNUS_DIR}/bin/cygnus-flume-ng
CYGNUS_USER=cygnus

cygnus_start()
{
    local result=0
    local cygnus_instance=${1}

    if [[ ! -x ${FLUME_EXECUTABLE} ]]; then
        printf "%s\n" "Fail - ${FLUME_EXECUTABLE} not exists or is not executable."
        exit 1
    fi

    if [[ $(ls -l ${CYGNUS_DIR}/conf/cygnus_instance_${cygnus_instance}*.conf 2> /dev/null | wc -l) -eq 0 ]]; then
        if [[ ${cygnus_instance} == "" ]]; then
            printf "%s\n" "There aren't any instance of Cygnus configured. Refer to file /usr/cygnus/conf/README.md for further information."
        else
            printf "%s\n" "There aren't any instance of Cygnus configured with the name ${cygnus_instance}. Refer to file /usr/cygnus/conf/README.md for further information."
        fi
        return 1
    fi

    for instance in $(ls ${CYGNUS_DIR}/conf/cygnus_instance_${cygnus_instance}*.conf)
    do
        local NAME
        NAME=${instance%.conf}
        NAME=${NAME#*cygnus_instance_}

        . ${instance}
        
        CYGNUS_PID_FILE="/var/run/cygnus/cygnus_${NAME}.pid"
        
        printf "%s" "Starting Cygnus ${NAME}...  "

        status -p ${CYGNUS_PID_FILE} ${FLUME_EXECUTABLE} &> /dev/null 

        if [[ ${?} -eq 0 ]]; then
            printf "%s\n" " Already running, skipping $(success)"
            continue
        fi

        CYGNUS_COMMAND="${FLUME_EXECUTABLE} agent -p ${ADMIN_PORT} --conf ${CONFIG_FOLDER} -f ${CONFIG_FILE} -n ${AGENT_NAME}  -Dflume.log.file=${LOGFILE_NAME} -Duser.timezone=UTC -Dfile.encoding=UTF-8 &>> /var/log/cygnus/${LOGFILE_NAME} & echo \$! > ${CYGNUS_PID_FILE}"
        su ${CYGNUS_USER} -c "${CYGNUS_COMMAND}"
        sleep 2 # wait some time to know if flume is still alive
        PID=$(cat ${CYGNUS_PID_FILE})        
        FLUME_PID=$(ps -ef | grep -v "grep" | grep "${PID:-not_found}")
        if [[ -z ${FLUME_PID} ]]; then
            printf "%s\n" "$(failure)"
            result=$((${result}+1))
            rm ${CYGNUS_PID_FILE}
        else
            chown ${CYGNUS_USER}:${CYGNUS_USER} ${CYGNUS_PID_FILE}
            printf "%s\n" "$(success)"
        fi
    done
    return ${result}
}

cygnus_stop()
{
    local result=0
    local cygnus_instance=${1}

    if [[ $(ls -l /var/run/cygnus/cygnus_${cygnus_instance}*.pid 2> /dev/null | wc -l) -eq 0 ]]; then
        printf "%s\n" "There aren't any instance of Cygnus ${cygnus_instance} running $(success)"
        return 0
    fi

    for run_instance in $(ls /var/run/cygnus/cygnus_${cygnus_instance}*.pid)
    do

        local NAME
        NAME=${run_instance%.pid}
        NAME=${NAME#*cygnus_}

        printf "%-50s" "Stopping Cygnus ${NAME}..."
        PID=$(cat ${run_instance})        
        kill -HUP ${PID} &> /dev/null
        sleep 2
        FLUME_PID=$(ps -ef | grep -v "grep" | grep "${PID:-not_found}")
        if [[ -z ${FLUME_PID} ]]; then
            rm -f ${run_instance}
            printf "%s\n" "$(success)"
        else
            printf "%s\n" "$(failure)"
            result=$((${result}+1))
            rm -f ${run_instance}
        fi
    done
    return ${result}
}

cygnus_status()
{
    local result=0
    local cygnus_instance=${1}

    if [[ $(ls -l /var/run/cygnus/cygnus_${cygnus_instance}*.pid 2> /dev/null | wc -l) -eq 0 ]]; then
        printf "%s\n" "There aren't any instance of Cygnus ${cygnus_instance} running"
        exit 1
    fi

    for run_instance in $(ls /var/run/cygnus/cygnus_${cygnus_instance}*.pid)
    do

        local NAME
        NAME=${run_instance%.pid}
        NAME=${NAME#*cygnus_}

        printf "%s\n" "Cygnus ${NAME} status..."
        status -p ${run_instance} ${FLUME_EXECUTABLE}
        result=$((${result}+${?}))

    done
    return ${result}
}


case ${PARAM} in

    'start')
        cygnus_start ${CYGNUS_INSTANCE}
        ;;

    'stop')
        cygnus_stop ${CYGNUS_INSTANCE}
        ;;

    'restart')
        cygnus_stop ${CYGNUS_INSTANCE}
        cygnus_start ${CYGNUS_INSTANCE}
        ;;

    'status')
        cygnus_status ${CYGNUS_INSTANCE}
        ;;

esac
