FORMAT: 1A
HOST: http://fiware-ngsi2.apiblueprint.org/

# FIWARE-NGSI Simple API (v1) Cookbook

FIWARE-NGSI Simple API (v1) Cookbook.

This is a cookbook with recipes that show how to use FIWARE cygnus API.
Use this examples for learning and enjoy!

This is a work in progress and is changing on a daily basis.

Please check the following [FIWARE Open Specification Legal Notice (implicit patents license)]
(http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/FI-WARE_Open_Specification_Legal_Notice_(implicit_patents_license))
to understand the rights to use this document.

# Group API Root

This resource allows you to obtain a list of subresources published by the API:

* version of the current running cygnus on your system
* statistics about the configured Flume components
* useful information about configured grouping rules like:
  * current grouping rules configured
  * add, update or delete current grouping rules

# Gets version of current Cygnus [GET /v1/version]

+ Response 200 (application/json)

      [
          {
              "success": "true",
              "version": "0.12.0_SNAPSHOT.52399574ea8503aa8038ad14850380d77529b550"
          }
      ]

# Get stats of Flume commponents [GET /v1/stats]

+ Response 200 (application/json)

      [
          {
              "stats": {
              "channels": [
                    {
                        "name": "mysql-channel",
                        "num_events": 0,
                        "num_puts_failed": 0,
                        "num_puts_ok": 11858,
                        "num_takes_failed": 1,
                        "num_takes_ok": 11858,
                        "setup_time": "2016-02-05T10:34:25.80Z",
                        "status": "START"
                    }
                  ],
              "sinks": [
                    {
                        "name": "mysql-sink",
                        "num_persisted_events": 11800,
                        "num_processed_events": 11858,
                        "setup_time": "2016-02-05T10:34:24.978Z",
                        "status": "START"
                    }
                  ],
              "sources": [
                    {
                        "name": "http-source",
                        "num_processed_events": 11858,
                        "num_received_events": 11858,
                        "setup_time": "2016-02-05T10:34:24.921Z",
                        "status": "START"
                    }
                  ]
              },
              "success": "true"
          }
      ]


# Get current grouping rules [GET /v1/groupingrules]

+ Response 200 (application/json)

        [
            {
                "grouping_rules": [
                        {
                            "destination": "allcars",
                            "fields": [
                                  "entityType"
                                  ],
                            "fiware_service_path": "cars",
                            "id": 1,
                            "regex": "Car"
                        },
                        {
                             "destination": "allrooms",
                             "fields": [
                                  "entityType"
                                  ],
                            "fiware_service_path": "rooms",
                            "id": 2,
                            "regex": "Room"
                        }
                    ],
                "success": "true"
            }
        ]

# Update an already existent grouping rules [PUT /v1/groupingrules]

+ Response 200 (application/json)

        [
            {"success":"true"}
        ]


# Delete a grouping rules [DELETE /v1/groupingrules]

+ Response 200 (application/json)

        [
            {"success":"true"}
        ]
