FORMAT: 1A
HOST: http://cygnus.lab.fiware.org/

# FIWARE-Cygnus API (v1)

FIWARE-CYGNUS API (v1).

This is a cookbook with commands that show how to use FIWARE cygnus API.
It's a work in progress and is changing on a daily basis.

Please check the following [FIWARE Open Specification Legal Notice: implicit patents license](http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/FI-WARE_Open_Specification_Legal_Notice_%28implicit_patents_license%29)
to understand the rights to use this document.


# Description

This resource allows you to obtain a list of subresources published by the API:

* version of the current running cygnus on your system
* statistics about the configured Flume components
* useful information about configured grouping rules like:
  * current grouping rules configured
  * add, update or delete current grouping rules

# Error responses

Error list (HTTP response code in parenthesis):

* BadFields             (`400`). The incoming JSON payload cannot be parsed.
* WrongFields           (`400`). The incoming request has invalid fields.
* WrongSubscription     (`400`). Orion cant do the subscription.
* BadRequest            (`400`). The request is invalid.
* InternalServerError   (`500`). Internal error in the server.

# Group Version API

## Getting the version of Cygnus [/Version API]

### "GET /v1/version" [GET]

+ Request

       GET http://<cygnus_host>:<management_port>/v1/version

+ Response 200 (application/json)

       [
            {
              "success": "true",
              "version": "0.13.0_SNAPSHOT.52399574ea8503aa8038ad14850380d77529b550"
            }
       ]

# Group Statistics API.

## Methods [/Statistics API]
Allowed operations with API statistics:

### "GET /v1/stats" [GET /v1/stats]
Information can be retrieved by GET statistics method, which you can retrieve all the information of the flume component.

+ Request

       GET http://<cygnus_host>:<management_port>/v1/stats

+ Response 200 (application/json)

       [
          {
              "stats": {
              "channels": [
                    {
                        "name": "mysql-channel",
                        "num_events": 0,
                        "num_puts_failed": 0,
                        "num_puts_ok": 11858,
                        "num_takes_failed": 1,
                        "num_takes_ok": 11858,
                        "setup_time": "2016-02-05T10:34:25.80Z",
                        "status": "START"
                    }
                  ],
              "sinks": [
                    {
                        "name": "mysql-sink",
                        "num_persisted_events": 11800,
                        "num_processed_events": 11858,
                        "setup_time": "2016-02-05T10:34:24.978Z",
                        "status": "START"
                    }
                  ],
              "sources": [
                    {
                        "name": "http-source",
                        "num_processed_events": 11858,
                        "num_received_events": 11858,
                        "setup_time": "2016-02-05T10:34:24.921Z",
                        "status": "START"
                    }
                  ]
              },
              "success": "true"
          }
        ]

### "PUT /v1/stats" [PUT /v1/stats]
Statistics can be reset by a PUT request.

+ Request

       PUT http://<cygnus_host>:<management_port>/v1/stats

+ Response 200 (application/json)

        {
            "success":"true"
        }

# Name Mappings Rules API
API operations used to manage the name mappings of Cygnus.

## Methods [/Name Mappings API]

### "GET /v1/namemappings" [GET /v1/namemappings]
Name mappings can be retrieved by GET methods.

+ Request

      GET http://<cygnus_host>:<management_port>/v1/namemappings

+ Response 200 (application/json)

        {
            "success":"true",
            "serviceMapping": [
                {
                    "originalService":"service",
                    "newService":"newService",
                    "servicePathMappings": [
                        {
                            "originalServicePath":"/servicePath",
                            "newServicePath":"/newServicePath",
                            "entityMappings": [
                                {
                                    "originalEntityId":"Room1",
                                    "originalEntityType":"Room",
                                    "newEntityId":"BigRoom1",
                                    "newEntityType":"BigRoom",
                                    "attributeMappings":[
                                        {
                                            "originalAttributeName":"temperature",
                                            "originalAttributeType":"float",
                                            "newAttributeName":"bedsNumber",
                                            "newAttributeType":"integer"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }


### "POST /v1/namemappings" [POST /v1/namemappings]
Name mappings can be provisioned by POST methods.

+ Request

      POST http://<cygnus_host>:<management_port>/v1/namemappings
       {
            "serviceMapping": [
                {
                    "originalService":"service",
                    "newService":"newService",
                    "servicePathMappings": [
                        {
                            "originalServicePath":"/servicePath",
                            "newServicePath":"/newServicePath",
                            "entityMappings": [
                                {
                                    "originalEntityId":"Room1",
                                    "originalEntityType":"Room",
                                    "newEntityId":"BigRoom1",
                                    "newEntityType":"BigRoom",
                                    "attributeMappings":[
                                        {
                                            "originalAttributeName":"temperature",
                                            "originalAttributeType":"float",
                                            "newAttributeName":"bedsNumber",
                                            "newAttributeType":"integer"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
            }

+ Response 200 (application/json)

        {
            "success":"true",
        }

### "PUT /v1/namemappings" [PUT /v1/namemappings]
Name mappings can be modified by PUT methods.

+ Request

      PUT http://<cygnus_host>:<management_port>/v1/namemappings
       {
            "serviceMapping": [
                {
                    "originalService":"service",
                    "newService":"newService",
                    "servicePathMappings": [
                        {
                            "originalServicePath":"/servicePath",
                            "newServicePath":"/newServicePath",
                            "entityMappings": [
                                {
                                    "originalEntityId":"Room1",
                                    "originalEntityType":"Room",
                                    "newEntityId":"BigRoom1",
                                    "newEntityType":"BigRoom",
                                    "attributeMappings":[
                                        {
                                            "originalAttributeName":"temperature",
                                            "originalAttributeType":"float",
                                            "newAttributeName":"bedsNumber",
                                            "newAttributeType":"integer"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
            }

+ Response 200 (application/json)
        {
            "success":"true",
            "serviceMapping": [
                {
                    "originalService":"service",
                    "newService":"newService",
                    "servicePathMappings": [
                        {
                            "originalServicePath":"/servicePath",
                            "newServicePath":"/newServicePath",
                            "entityMappings": [
                                {
                                    "originalEntityId":"Room1",
                                    "originalEntityType":"Room",
                                    "newEntityId":"BigRoom1",
                                    "newEntityType":"BigRoom",
                                    "attributeMappings":[
                                        {
                                            "originalAttributeName":"temperature",
                                            "originalAttributeType":"float",
                                            "newAttributeName":"bedsNumber",
                                            "newAttributeType":"integer"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }

### "DELETE /v1/namemappings" [DELETE /v1/namemappings]
Name mappings can be deleted by DELETE methods.

+ Request

      DELETE http://<cygnus_host>:<management_port>/v1/namemappings
       {
            "serviceMapping": [
                {
                    "originalService":"service",
                    "newService":"newService",
                    "servicePathMappings": [
                        {
                            "originalServicePath":"/servicePath",
                            "newServicePath":"/newServicePath",
                            "entityMappings": [
                                {
                                    "originalEntityId":"Room1",
                                    "originalEntityType":"Room",
                                    "newEntityId":"BigRoom1",
                                    "newEntityType":"BigRoom",
                                    "attributeMappings":[
                                        {
                                            "originalAttributeName":"temperature",
                                            "originalAttributeType":"float",
                                            "newAttributeName":"bedsNumber",
                                            "newAttributeType":"integer"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
            }

+ Response 200 (application/json)

        {
            "success":"true",
        }

# Group Grouping Rules API
API operations used to manage the grouping rules of Cygnus.

## Methods [/Grouping Rules API]

### "GET /v1/groupingrules" [GET /v1/groupingrules]
Grouping rules can be retrieved by GET methods.

+ Request

       GET http://<cygnus_host>:<management_port>/v1/groupingrules

+ Response 200 (application/json)

        [
            {
                "grouping_rules": [
                        {
                            "destination": "allcars",
                            "fields": [
                                  "entityType"
                                  ],
                            "fiware_service_path": "cars",
                            "id": 1,
                            "regex": "Car"
                        },
                        {
                             "destination": "allrooms",
                             "fields": [
                                  "entityType"
                                  ],
                            "fiware_service_path": "rooms",
                            "id": 2,
                            "regex": "Room"
                        }
                    ],
                "success": "true"
            }
        ]

### "PUT /v1/groupingrules" [PUT /v1/groupingrules]
A grouping rule can be updated by PUT method.

+ Parameters

       + id: 1 (number) - An unique identifier of the message.

+ Request

       PUT http://<cygnus_host>:<management_port>/v1/groupingrules=id=1
       {
           "regex": "Room",
           "destination": "otherrooms",
           "fiware_service_path": "rooms",
           "fields": ["entityType"]
      }

+ Response 200 (application/json)

        [
            {"success":"true"}
        ]

### "POST /v1/groupingrules" [POST /v1/groupingrules]
A grouping rule can be added by POST method.

+ Parameters

       + id: 1 (number) - An unique identifier of the message.

+ Request

       POST http://<cygnus_host>:<management_port>/v1/groupingrules
       {
           "regex": "Room",
           "destination": "allrooms",
           "fiware_service_path": "rooms",
           "fields": ["entityType"]
       }

+ Response 200 (application/json)

       {
           "success":"true"
       }

### "DELETE /v1/groupingrules" [DELETE /v1/groupingrules]
A grouping rule can be deleted by DELETE method.

+ Parameters

       + id: 1 (number) - An unique identifier of the message.

+ Request

       DELETE http://<cygnus_host>:<management_port>/v1/groupingrules?id=2

+ Response 200 (application/json)

       [
           {"success":"true"}
       ]


# Group Subscriptions API

## Methods [/Subscriptions API]
API operations used to manage subscriptions without interact with Orion. There are some allowed operations like POST new subscriptions (ngsi_version 1 and 2), GET current subscriptions (by ID or delete all) or DELETE by ID.

### "GET /v1/subscriptions?ngsi_version=2&subscription_id=<subscriptionId>" [GET /v1/subscriptions?ngsi_version=2&subscription_id=<subscriptionId>]

+ Parameters

       + ngsi_version: 2 (Defines the Orion API's version)
       + subscription_id: <subscriptionId> (Subscription's identificator)

+ Request

       GET http://<cygnus_host>:<management_port>/v1/subscriptions?ngsi_version=<ngsiVersion>&subscription_id=<subscriptionId>
       {
               "host":"orion.lab.fi-ware.org",
               "port":"1026",
               "ssl":"false",
               "xauthtoken":"QsENv67AJj7blC2rt54ESc5hMWYrs"
       }

+ Response 200 (application/json)

       {
               "success":"true",
               "result" : {
                       {
                               "notification":{
                                       "lastNotification":"2015-07-28T22:24:33.00Z",
                                       "timesSent":8122767998226748692,
                                       "callback":"http:\/\/xxx.xxx.xx.xxx:xxxx\/ngsi10\/notifyContext",
                                       "attributes":[
                                       ]
                               },
                               "expires":"2016-09-25T08:17:47.00Z",
                               "subject":{
                                       "condition":{
                                               "expression":{
                                                       "q":"",
                                                       "geometry":"",
                                                       "coords":"",
                                                       "georel":""
                                               },
                                               "attributes":[
                                                       "TimeInstant"
                                               ]
                                       },
                                       "entities":[
                                               {
                                                       "id":"",
                                                       "type":"sevilla:fountain",
                                                       "idPattern":"patternId"
                                               }
                                       ]
                               },
                               "id":"54325022q469a3873d30oe95",
                               "status":"active"
                       }
               }
       }

+ Response 400 (application/json)

       {
               "success":"false",
               "result" : {
                       {
                               "description":"",
                               "error":"subscriptionId does not correspond to an active subscription"
                       }
               }
       }

+ Response 400 (application/json)

       {
               "success":"false",
               "error":"Parse error, invalid parameter (ngsi_version): Must be 1 or 2. Check it for errors."
       }

+ Response 400 (application/json)

       {
               "success":"false",
               "error":"GET /v1/subscriptions not implemented."
       }

### "GET /v1/subscriptions?ngsi_version=2" [GET /v1/subscriptions?ngsi_version=2]
Subscription can be retrieved by GET methods, retrieving all the subscriptions or retrieving one by its subscription ID.

+ Parameters

       + ngsi_version: 2 (defines the Orion API's version)

+ Request

       GET http://<cygnus_host>:<management_port>/v1/subscriptions?ngsi_version=<ngsiVersion>
       {
               "host":"orion.lab.fi-ware.org",
               "port":"1026",
               "ssl":"false",
               "xauthtoken":"QsENv67AJj7blC2rt54ESc5hMWYrs"
       }

+ Response 200 (application/json)

       {
              {
                   "success":"true",
                   "result" : {
                        {
                             "result":[
                                   {
                                       "notification":{
                                            "lastNotification":"2015-07-28T22:23:30.00Z",
                                            "timesSent":7126568376946155044,
                                            "http":{
                                                 "url":"http:\/\/192.168.32.120:1026\/ngsi23\/notifyContext"
                                            },
                                            "attrs":[]
                                       },
                                       "expires":"2016-09-13T09:27:15.00Z",
                                       "subject":{
                                           "condition":{
                                                "attrs":[
                                                   "chlorine"
                                                ]
                                            },
                                            "entities":[
                                                {
                                                     "id":"",
                                                     "type":"sevilla:fountain",
                                                     "idPattern":"Sevilla:FUENTES:"
                                                }
                                            ]
                                        },
                                        "id":"54228e731860a3873d395d66",
                                        "status":"active"
                                    }
                              ]
                        }
                  }
              }
       }


+ Response 400 (application/json)

       {
            "success":"false",
            "error":"Parse error, invalid parameter (ngsi_version): Must be 1 or 2. Check it for errors."
       }

+ Response 400 (application/json)

       {
            "success":"false",
            "error":"GET /v1/subscriptions not implemented for NGSI version 1."
       }

+ Response 400 (application/json)

       {
            "success":"false",
            "error":"Invalid endpoint, field 'ssl' is missing"
       }

### "POST /v1/subscriptions?ngsi_version=1" [POST /v1/subscriptions?ngsi_version=1]

+ Parameters

       + ngsi_version: 1 (Defines the Orion API's version)

+ Request

       POST "http://<cygnus_host>:<management_port>/v1/subscriptions?ngsi_version=1"
       {
           "subscription":{
           "entities": [
                   {
                       "type": "Room",
                       "isPattern": "false",
                       "id": "Room1"
                   }
               ],
           "attributes": [],
           "reference": "http://<reference_host>:<reference_port>",
           "duration": "P1M",
           "notifyConditions": [
                   {
                       "type": "ONCHANGE",
                      "condValues": []
                   }
               ],
           "throttling": "PT5S"
           },
           "endpoint":{
                   "host":"<endpoint_host>",
                   "port":"<endpoint_port>",
                   "ssl":"false",
                   "xauthtoken":"234123123123123"
           }
       }

+ Response 200 (application/json)

        {
            "success":"true",
            "result" : {
                    {
                      "subscribeResponse":{
                                  "duration":"P1M",
                                  "throttling":"PT5S",
                                  "subscriptionId":"56f9081c3c6fb7e9d2a912a0"
                        }
                    }
              }
        }

+ Response 400 (application/json)

        {
            "success":"true",
            "result" : {
                    "subscribeError": {
                                "errorCode": {
                                        "code":"400",
                                        "reasonPhrase":"Bad Request",
                                        "details":"JSON Parse Error: unknown field: \/extraField"
                                }
                    }
            }
        }

+ Response 400 (application/json)

        {
            "success":"false",
            "error":"Invalid subscription, field 'duration' is empty"
        }

+ Response 400 (application/json)

        {
            "success":"false",
            "error":"Invalid subscription, field 'notifyConditions' is missing"
        }

### "POST /v1/subscriptions?ngsi_version=2" [POST /v1/subscriptions?ngsi_version=2]
Subscription can be created by POST methods, in `ngsi_version=1` and `ngsi_version=2`.

+ Parameters

       + ngsi_version: 2 (Defines the Orion API's version)

+ Request

       POST "http://<cygnus_host>:<management_port>/v1/subscriptions?ngsi_version=2"
       {
               "subscription":{
                       "description": "One subscription to rule them all",
                       "subject": {
                               "entities": [
                                       {
                                               "idPattern": ".*",
                                               "type": "Room"
                                       }
                               ],
                               "condition": {
                                       "attrs": [
                                              "temperature"
                                       ],
                                       "expression": {
                                               "q": "temperature>40"
                                       }
                               }
                       },
                       "notification": {
                              "http": {
                                      "url": "http://localhost:1234"
                               },
                               "attrs": [
                                       "temperature",
                                       "humidity"
                               ]
                       },
                       "expires": "2016-05-05T14:00:00.00Z","throttling": 5
               },
               "endpoint":{
                       "host":"orion.lab.fiware.org",
                       "port":"1026",
                       "ssl":"false",
                       "xauthtoken":"QsENv67AJj7blC2qJ0YvfSc5hMWYrs"
               }
       }

+ Response 201 (application/json)

       {
               "success":"true",
               "result" : {
                       "SubscriptionID" : "572ae23d20e1387832ed98d0"
               }
       }

+ Response 400 (application/json)

       {
               "success":"false",
               "error":"Invalid subscription, field 'xxxxxx' is missing"
       }

+ Response 400 (application/json)

       {
               "success":"false",
               "error":"Invalid subscription, field 'xxxxxx' has missing fields"
       }

+ Response 400 (application/json)

       {
               "success":"false",
               "error":"Missing endpoint"
       }

### "DELETE /v1/subscriptions" [DELETE /v1/subscriptions]
Subscriptions can be deleted by DELETE methods, deleting a subscription by its ID.

+ Parameters

       + ngsi_version: 1 or 2 (Defines the Orion API's version)
       + subscription_id: <subscriptionId> (Subscription's identificator)

+ Request

       DELETE "http://<cygnus_host>:<management_port>/v1/subscriptions?subscription_id=<subscriptionId>&ngsi_version=<ngsiVersion>"
       {
               "host":"orion.lab.fi-ware.org",
               "port":"1026",
               "ssl":"false",
               "xauthtoken":"QsENv67AJj7blC2rt54ESc5hMWYrs"
       }

+ Response 204 (application/json)

       {
               "success":"true",
               "result" : {
                       " Subscription deleted "
               }
       }

+ Response 400 (application/json) [Bad parameters]

       {
               "success":"false",
               "error":"Parse error, wrong parameter (subscription_id). Check it for errors."
       }

+ Response 400 (application/json) [Wrong subscription id in v1]

       {
               "success":"false",
               "result" : {
                       {
                             "subscriptionId":"571872a9c0585c7451571be4",
                             "statusCode":{
                                   "code":"404",
                                   "reasonPhrase":"No context element found",
                                   "details":"subscriptionId: \/571872a9c0585c7451571be4\/"
                             }
                       }
               }
       }

+ Response 400 (application/json) [Wrong subscription id in v2]

       {
               "success":"false",
               "result" : {
                       {
                             "description":"The requested subscription has not been found. Check id","error":"NotFound"
                       }
               }
       }

+ Response 400 (application/json) [Empty authentication token]

       {
               "success":"false",
               "error":"Empty Auth-Token. Required for API methods"
       }

+ Response 400 (application/json) [Missing authentication token]

       {
               "success":"false",
               "error":"Missing Auth-Token. Required for API methods"
       }


# Group Admin API

## Methods [/Group Admin API]
API operations used to get and update the logging level of Cygnus.

### "GET /admin/log" [GET /admin/log]
Logging level can be retrieved by GET method.

+ Request

       GET http://<cygnus_host>:<management_port>/admin/log

+ Response 200 (application/json)

       {
               "level": "..."
       }

+ Response 500 (application/json)

       {
               "error": "..."
       }

### "PUT /admin/log" [PUT /admin/log]
Logging level can be updated by PUT method.

+ Parameters

       + loglevel: Must be DEBUG, INFO, WARN, ERROR o FATAL (Defines the valid logging levels)

+ Request

       PUT http://<cygnus_host>:<management_port>/admin/log?level=<log_level>

+ Response 200 (text/plain)

       OK

+ Response 400 (application/json)

       {
           "error":"Invalid log level"
       }

+ Response 400 (application/json)

       {
           "error":""
       }

# Group Admin Loggers API

## Methods [/Admin Loggers API]
Group of API methods related with log4j loggers.

### "GET /v1/admin/log/loggers" [GET /v1/admin/log/loggers]

+ Parameters

       + transient: true, retrieving from memory, or false, retrieving from file (Defines the transient mode)

+ Request

       GET http://<cygnus_host>:<management_port>/v1/admin/log/loggers?transient=<transient_value>

+ Response 200 (text/plain)

       {
           "success":"true",
           "loggers":[
               {"name":"org.apache.hadoop","level":"WARN"},
               {"name":"org.apache.flume.node.AbstractConfigurationProvider"},
               {"name":"org.apache.kafka","level":"WARN"},
               ........
               {"name":"org.apache.hive","level":"INFO"}
           ]
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }


### "GET /v1/admin/log/loggers?name=<name>" [GET /v1/admin/log/loggers?name=<name>]
Loggers can be retrieved with GET methods, getting all loggers or getting one by its name.

+ Parameters

       + transient: true (retrieves from memory) or false (retrieves from file).
       + name: "logger_name" (Defines the name of the appender)

+ Request

       GET http://<cygnus_host>:<management_port>/v1/admin/log/loggers?transient=<transient_value>&name=<logger_name>

+ Response 200 (text/plain)

       {
           "success":"true",
           "loggers":[
               {"name":<logger_name>,"level":<logger_level>},
           ]
       }

+ Response 400 (application/json)

      {
          "success":"false",
          "result":"logger name not found"
      }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }

### "PUT /v1/admin/log/loggers" [PUT /v1/admin/log/loggers]
Loggers can be put with PUT methods. There are some special situations here: In `transient` mode only update is allowed. However, in no `transient` mode the put option is available, in addition to upgrading.

+ Parameters

       + transient: true, retrieving from memory, or false, retrieving from file (Defines the transient mode)

+ Request

       PUT http://<cygnus_host>:<management_port>/v1/admin/log/loggers?transient=<transient_value>
       {
          "logger": {
               "name":<logger_name>,
               "level":<logger_level>
          }
       }

+ Response 200 (text/plain)

       {
          "success":"true",
          "result":"Logger <logger_name> updated succesfully"
       }

+ Response 200 (application/json)

       {
           "success":"true",
           "result":"Logger <logger_name> put"
       }

+ Response 400 (application/json)

      {
          "success":"false",
          "result":"Loggers addition is  not implemented"
      }


+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Missing input JSON"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid input JSON"
       }

### "POST /v1/admin/log/loggers" [POST /v1/admin/log/loggers]
Loggers can be posted with POST methods. This situation only works in no `transient` mode, disabling the creation of new Loggers in memory.

+ Parameters

       + transient: true, retrieving from memory, or false, retrieving from file (Defines the transient mode)

+ Request

       POST http://<cygnus_host>:<management_port>/v1/admin/log/loggers?transient=<transient_value>
       {
          "logger": {
               "name":<logger_name>,
               "level":<logger_level>
          }
       }

+ Response 200 (text/plain)

       {
          "success":"true",
          "result":"Logger <logger_name> updated succesfully"
       }

+ Response 200 (application/json)

       {
           "success":"true",
           "result":"Logger <logger_name> posted"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"POST appenders in transient mode is not implemented"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Logger <logger_name> already exist"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Missing input JSON"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid input JSON"
       }

### "DELETE /v1/admin/log/loggers" [DELETE /v1/admin/log/loggers]

+ Parameters

       + transient: true, retrieving from memory, or false, retrieving from file (Defines the transient mode)

+ Request

       DELETE http://<cygnus_host>:<management_port>/v1/admin/log/loggers?name=<logger_name>

+ Response 200 (text/plain)

       {
           "success":"true",
           "result":"Loggers removed succesfully"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }

### "DELETE /v1/admin/log/loggers?name=<name>" [DELETE /v1/admin/log/loggers?name=<name>]
Loggers can be deleted with DELETE methods, deleting all Loggers or getting one by its name.

+ Parameters

       + transient: true, retrieving from memory, or false, retrieving from file (Defines the transient mode)
       + name: "logger_name" (Defines the name of the appender)

+ Request

       DELETE http://<cygnus_host>:<management_port>/v1/admin/log/loggers?name=<logger_name>

+ Response 200 (text/plain)

       {
           "success":"true",
           "result":"Logger <logger_name> removed succesfully"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }

# Group Admin Appenders API

## Methods [/Admin Appenders API]
Group of API methods related with log4j appenders.

### "GET /v1/admin/log/appenders" [GET /v1/admin/log/appenders]

+ Parameters

       + transient: true, retrieving from memory, or false, retrieving from file (Defines the transient mode)

+ Request

       GET http://<cygnus_host>:<management_port>/v1/admin/log/appenders?transient=<transient_value>

+ Response 200 (text/plain)

       {
           "success":"true",
           "appenders":[
               {
                   "name":"console",
                   "layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n"
               }
           ]
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }

### "GET /v1/admin/log/appenders?name=<name>" [GET /v1/admin/log/appenders?name=<name>]
Appenders can be retrieved with GET methods, getting all appenders or getting one by its name.

+ Parameters

       + transient: true, retrieving from memory, or false, retrieving from file (Defines the transient mode)
       + name: "appender_name" (Defines the name of the appender)

+ Request

       GET http://<cygnus_host>:<management_port>/v1/admin/log/appenders?transient=<transient_value>&name=<appender_name>

+ Response 200 (text/plain)

       {
           "success":"true",
           "appender":[
               {
                   "name":<appender_name>,
                   "layout":"time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | corr=%X{correlatorId} | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n"
               }
           ]
       }

+ Response 400 (application/json)

      {
          "success":"false",
          "result":"Appender name not found"
      }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }

### "PUT /v1/admin/log/appenders" [PUT /v1/admin/log/appenders]
Appenders can be put with PUT methods. There are some special situations here: In `transient` mode only update is allowed. However, in no `transient` mode the put option is available, in addition to upgrading.

+ Parameters

       + transient: true, retrieving from memory, or false, retrieving from file (Defines the transient mode)

+ Request

       PUT http://<cygnus_host>:<management_port>/v1/admin/log/appenders?transient=<transient_value>
       {
           "appender": {
               "name":<appender_name>,
               "class":<appender_class>
           },
           "pattern": {
               "layout":<appender_layout>,
               "ConversionPattern":"<appender_conversion_pattern>
           }
       }

+ Response 200 (text/plain)

       {
          "success":"true",
          "result":"Appender <appender_name> updated succesfully"
       }

+ Response 200 (application/json)

       {
           "success":"true",
           "result":"Appender <appender_name> put"
       }

+ Response 400 (application/json)

      {
          "success":"false",
          "result":"Appenders addition is  not implemented"
      }


+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Appenders addition is not implemented"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Missing input JSON"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid input JSON"
       }

### "POST /v1/admin/log/appenders" [POST /v1/admin/log/appenders]
Appenders can be posted with POST methods. This situation only works in no `transient` mode, disabling the creation of new Appenders in memory.

+ Parameters

       + transient: true, retrieving from memory, or false, retrieving from file (Defines the transient mode)

+ Request

       POST http://<cygnus_host>:<management_port>/v1/admin/log/appenders?transient=<transient_value>
       {
           "appender": {
               "name":<appender_name>,
               "class":<appender_class>
           },
           "pattern": {
               "layout":<appender_layout>,
               "ConversionPattern":"<appender_conversion_pattern>
           }
       }

+ Response 200 (text/plain)

       {
          "success":"true",
          "result":"Appender <appender_name> updated succesfully"
       }

+ Response 200 (application/json)

       {
           "success":"true",
           "result":"Appender <appender_name> posted"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"POST appenders in transient mode is not implemented"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Appender <appender_name> already exist"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Missing input JSON"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid input JSON"
       }

### "DELETE /v1/admin/log/appenders" [DELETE /v1/admin/log/appenders]

+ Parameters

       + transient: true, retrieving from memory, or false, retrieving from file (Defines the transient mode)

+ Request

       DELETE http://<cygnus_host>:<management_port>/v1/admin/log/appenders

+ Response 200 (text/plain)

       {
           "success":"true",
           "result":"Appenders removed succesfully"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }

### "DELETE /v1/admin/log/appenders?name=<name>" [DELETE /v1/admin/log/appenders?name=<name>]
Appenders can be deleted with DELETE methods, deleting all appenders or getting one by its name.

+ Parameters

       + transient: true, retrieving from memory, or false, retrieving from file (Defines the transient mode)
       + name: "appender_name" (Defines the name of the appender)

+ Request

       DELETE http://<cygnus_host>:<management_port>/v1/admin/log/appenders?name=<appender_name>

+ Response 200 (text/plain)

       {
           "success":"true",
           "result":"Appender <appender_name> removed succesfully"
       }

+ Response 400 (application/json)

       {
           "success":"false",
           "result":"Invalid 'transient' parameter found"
       }
